steps:
  # 1) Build the image and tag as latest at the fixed Artifact Registry URL
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - "us-central1-docker.pkg.dev/code-battlegrounds/poc-app/app:latest"
      - .

  # 2) Push the image to Artifact Registry
  - name: gcr.io/cloud-builders/docker
    args: ["push", "us-central1-docker.pkg.dev/code-battlegrounds/poc-app/app:latest"]

  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -f
      - Dockerfile.migrate
      - -t
      - "us-central1-docker.pkg.dev/code-battlegrounds/poc-app/migrate:latest"
      - .

  # 4) Push migration image
  - name: gcr.io/cloud-builders/docker
    args: ["push", "us-central1-docker.pkg.dev/code-battlegrounds/poc-app/migrate:latest"]


images:
  - "us-central1-docker.pkg.dev/code-battlegrounds/poc-app/app:latest"
  - "us-central1-docker.pkg.dev/code-battlegrounds/poc-app/migrate:latest"
timeout: "1200s" # 20 minutes
