/* eslint-disable @typescript-eslint/no-require-imports */


const { createServer } = require('http');
const next = require('next');
const { Server } = require('socket.io');

// Configure environment
const dev = process.env.NODE_ENV !== 'production';
const hostname = 'localhost';
const port = 3000;

// Initialize the Next.js app

// this is starting up next.js
const app = next({ dev, hostname, port });

// any web traffic like asking for a page load will be handled by next.js
const handle = app.getRequestHandler();

// wait for next.js to be ready before starting our server
app.prepare().then(() => {
    // creating an httpServer and passing all traffic to next.js to handle (like page loads)
  const httpServer = createServer(handle);

  // Initialize Socket.IO server and attach it to our HTTP server.
  // This allows Socket.IO to handle WebSocket connections on the same server that serves our Next.js app.
  const io = new Server(httpServer);

  // Listen for socket connections
  io.on('connection', (socket) => {
    // socket.id is a unique value for each client, auto-generated by socket.io
    console.log(`New connection: ${socket.id}`);

    // 1. Handle joining a specific game room
    socket.on('joinGame', (gameId) => {
      socket.join(gameId);
      
      // Determine how many people are currently in this specific room
      const room = io.sockets.adapter.rooms.get(gameId);
      const numPlayers = room ? room.size : 0;

      // Role Assignment Logic
      let role = 'spectator';
      if (numPlayers === 1) {
        role = 'coder';   // First person in
      } else if (numPlayers === 2) {
        role = 'tester';  // Second person in
      }

      // Emit the assigned role back ONLY to the person who just joined
      socket.emit('roleAssigned', role);
      
      console.log(`Socket ${socket.id} joined room ${gameId} as ${role}`);
    });

    // 2. Handle live code relay (Coder -> Server -> Tester)
    socket.on('codeChange', (data) => {
      console.log(`Server received code for room ${data.roomId}`); // <-- ADD THIS
      // Broadcast the updated code to everyone else in the same room (except the sender)
      socket.to(data.roomId).emit('receiveCodeUpdate', data.code);
    });

    // 3. Handle graceful disconnection
    socket.on('disconnect', () => {
      console.log(`Disconnected: ${socket.id}`);
    });
  });

  // Start the unified server
  httpServer.listen(port, () => {
    console.log(`Code BattleGrounds Server Ready on http://${hostname}:${port}`);
  });


});