import Head from "next/head";
import styles from "@/styles/Home.module.css";

import Editor from "@monaco-editor/react";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <div
        className={`${styles.page}`}
      >
        <div className={styles.editorWrapper}>
          <Editor
            height="100%"
            theme="vs-dark"
            defaultLanguage="typescript"
            options={{
              minimap: { enabled: false }
            }}
          />
        </div>
      </div>
    </>
  );
}
